remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ML Configurations
description: A small, highly opinionated python tool to handle configurations for machine learning pipelines.
show_downloads: true
